/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dangNhapdangKy;

import javax.swing.JOptionPane;
import connectionSQLServer.connection;
import java.sql.Connection;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import trangchu.TrangChu;
import session.sessionSinhVien;
import javax.swing.SwingWorker;

/**
 *
 * @author admin
 */
public class DangNhapSV extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DangNhapSV.class.getName());

    /**
     * Creates new form DangNhap
     */
    public DangNhapSV() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(245, 246, 248));
        getRootPane().setDefaultButton(btnLogin);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(28, 32, 28, 32));
        lblLogo = new javax.swing.JLabel();
        lblLogo.setHorizontalAlignment(0);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ptit-logo.png")));
        titleDe2 = new javax.swing.JLabel();
        titleDe2.setText("THI TRẮC NGHIỆM");
        titleDe2.setFont(new java.awt.Font("Segoe UI", 1, 24));
        titleDe2.setForeground(new java.awt.Color(205, 32, 45));
        titleDe2.setHorizontalAlignment(0);
        titleDangNhap = new javax.swing.JLabel();
        titleDangNhap.setText("Đăng nhập sinh viên");
        titleDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 15));
        titleDangNhap.setForeground(new java.awt.Color(107, 114, 128));
        titleDangNhap.setHorizontalAlignment(0);
        titleLLogin = new javax.swing.JLabel();
        titleLLogin.setText("Mã sinh viên");
        titleLLogin.setFont(new java.awt.Font("Segoe UI", 1, 14));
        titleLLogin.setForeground(new java.awt.Color(36, 43, 54));
        txtMaSV = new javax.swing.JTextField();
        txtMaSV.setFont(new java.awt.Font("Segoe UI", 0, 16));
        txtMaSV.setForeground(new java.awt.Color(36, 43, 54));
        txtMaSV.setBackground(new java.awt.Color(255, 255, 255));
        txtMaSV.setPreferredSize(new java.awt.Dimension(400, 44));
        txtMaSV.setToolTipText("Nhập mã sinh viên của bạn");
        btnLogin = new javax.swing.JButton();
        btnLogin.setText("Đăng nhập");
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 15));
        btnLogin.setBackground(new java.awt.Color(205, 32, 45));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setOpaque(true);
        btnLogin.setContentAreaFilled(true);
        btnLogin.setBorderPainted(false);
        btnLogin.setFocusPainted(false);
        jPanel5 = new javax.swing.JPanel();
        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 12, 0));
        bthGVLogin = new javax.swing.JButton();
        bthGVLogin.setText("Đăng nhập giảng viên");
        bthGVLogin.setFont(new java.awt.Font("Segoe UI", 0, 13));
        bthGVLogin.setBackground(new java.awt.Color(245, 246, 248));
        bthGVLogin.setForeground(new java.awt.Color(107, 114, 128));
        bthGVLogin.setOpaque(true);
        bthGVLogin.setContentAreaFilled(true);
        bthGVLogin.setBorderPainted(false);
        bthGVLogin.setFocusPainted(false);
        jPanel5.add(bthGVLogin);
        btnExit = new javax.swing.JButton();
        btnExit.setText("Thoát");
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 13));
        btnExit.setBackground(new java.awt.Color(245, 246, 248));
        btnExit.setForeground(new java.awt.Color(107, 114, 128));
        btnExit.setOpaque(true);
        btnExit.setContentAreaFilled(true);
        btnExit.setBorderPainted(false);
        btnExit.setFocusPainted(false);
        jPanel5.add(btnExit);
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        bthGVLogin.addActionListener(this::bthGVLoginActionPerformed);
        btnExit.addActionListener(this::btnExitActionPerformed);


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/ptit-logo.png")).getImage());
        setTitle("PTIT | Đăng nhập sinh viên");

        javax.swing.GroupLayout cardLayout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(cardLayout);
        cardLayout.setHorizontalGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleDe2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleLLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtMaSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        cardLayout.setVerticalGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(titleDe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(6, 6, 6)
            .addComponent(titleDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28)
            .addComponent(titleLLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(8, 8, 8)
            .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24)
            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bthGVLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthGVLoginActionPerformed
        // TODO add your handling code here:
        DangNhap gv = new DangNhap();
        gv.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_bthGVLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (!btnLogin.isEnabled()) {
            return;
        }
        String maSV = txtMaSV.getText().trim();
        if(maSV.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sinh viên !");
            return;
        }
        btnLogin.setEnabled(false);
        bthGVLogin.setEnabled(false);
        btnLogin.setText("Đang đăng nhập...");

        // Chạy SQL ở nền để cửa sổ không bị đơ.
        new SwingWorker<Void, Void>() {
            sessionSinhVien sinhVien;
            String thongBao;

            @Override
            protected Void doInBackground() {
                try (Connection ketnoi = connection.getConnectionSV()) {
                    if (ketnoi == null) {
                        thongBao = "Không thể kết nối tới SQL Server !";
                        return null;
                    }
                    try (CallableStatement cs = ketnoi.prepareCall("{call dbo.SP_LoginSinhVien(?)}")) {
                        cs.setQueryTimeout(15);
                        cs.setString(1, maSV);
                        try (ResultSet rs = cs.executeQuery()) {
                            if (rs.next()) {
                                sinhVien = new sessionSinhVien();
                                sinhVien.setHo(rs.getString("HO").trim());
                                sinhVien.setMaLop(rs.getString("MALOP").trim());
                                sinhVien.setMaSV(maSV);
                                sinhVien.setTen(rs.getString("TEN"));
                                sinhVien.setNgaySinh(rs.getString("NGAYSINH"));
                                sinhVien.setDiaChi(rs.getString("DIACHI"));
                                sinhVien.setTenLop(rs.getString("TENLOP"));
                                thongBao = "Đăng nhập thành công!\nChào mừng "
                                        + sinhVien.getHo() + " " + sinhVien.getTen() + " !";
                            } else {
                                thongBao = "Mã sinh viên không tồn tại!";
                            }
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    sinhVien = null;
                    thongBao = "Lỗi đăng nhập: " + e.getMessage();
                }
                return null;
            }

            // SQL làm xong thì hiện thông báo và mở trang chủ.
            @Override
            protected void done() {
                btnLogin.setText("Đăng nhập");
                btnLogin.setEnabled(true);
                bthGVLogin.setEnabled(true);
                if (!isDisplayable()) {
                    return;
                }
                JOptionPane.showMessageDialog(DangNhapSV.this, thongBao);
                if (sinhVien != null) {
                    TrangChu tc = new TrangChu(sinhVien);
                    tc.setVisible(true);
                    DangNhapSV.this.dispose();
                }
            }
        }.execute();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DangNhapSV().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel titleDe2;
    private javax.swing.JLabel titleDangNhap;
    private javax.swing.JLabel titleLLogin;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton bthGVLogin;
    private javax.swing.JButton btnExit;
    // End of variables declaration//GEN-END:variables
}
