/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dangNhapdangKy;
import connectionSQLServer.connection;
import java.sql.Connection;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import session.sessionGiaoVien;
import trangchu.TrangChu;
/**
 *
 * @author admin
 */
public class DangNhap extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DangNhap.class.getName());

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(245, 246, 248));
        getRootPane().setDefaultButton(btnLogin);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(28, 32, 28, 32));
        lblLogo = new javax.swing.JLabel();
        lblLogo.setHorizontalAlignment(0);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ptit-logo.png")));
        titleDe2 = new javax.swing.JLabel();
        titleDe2.setText("THI TRẮC NGHIỆM");
        titleDe2.setFont(new java.awt.Font("Segoe UI", 1, 24));
        titleDe2.setForeground(new java.awt.Color(205, 32, 45));
        titleDe2.setHorizontalAlignment(0);
        titleDangNhap = new javax.swing.JLabel();
        titleDangNhap.setText("Đăng nhập giảng viên");
        titleDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 15));
        titleDangNhap.setForeground(new java.awt.Color(107, 114, 128));
        titleDangNhap.setHorizontalAlignment(0);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setText("Tài khoản");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel4.setForeground(new java.awt.Color(36, 43, 54));
        gvLogin = new javax.swing.JTextField();
        gvLogin.setFont(new java.awt.Font("Segoe UI", 0, 16));
        gvLogin.setForeground(new java.awt.Color(36, 43, 54));
        gvLogin.setBackground(new java.awt.Color(255, 255, 255));
        gvLogin.setPreferredSize(new java.awt.Dimension(400, 44));
        gvLogin.setToolTipText("Nhập tài khoản giảng viên");
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setText("Mật khẩu");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel3.setForeground(new java.awt.Color(36, 43, 54));
        gvPassword = new javax.swing.JPasswordField();
        gvPassword.setFont(new java.awt.Font("Segoe UI", 0, 16));
        gvPassword.setForeground(new java.awt.Color(36, 43, 54));
        gvPassword.setBackground(new java.awt.Color(255, 255, 255));
        gvPassword.setPreferredSize(new java.awt.Dimension(400, 44));
        gvPassword.setToolTipText("Nhập mật khẩu");
        btnLogin = new javax.swing.JButton();
        btnLogin.setText("Đăng nhập");
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 15));
        btnLogin.setBackground(new java.awt.Color(205, 32, 45));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setOpaque(true);
        btnLogin.setContentAreaFilled(true);
        btnLogin.setBorderPainted(false);
        btnLogin.setFocusPainted(false);
        jPanel5 = new javax.swing.JPanel();
        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 12, 0));
        btnSVLogin = new javax.swing.JButton();
        btnSVLogin.setText("Đăng nhập sinh viên");
        btnSVLogin.setFont(new java.awt.Font("Segoe UI", 0, 13));
        btnSVLogin.setBackground(new java.awt.Color(245, 246, 248));
        btnSVLogin.setForeground(new java.awt.Color(107, 114, 128));
        btnSVLogin.setOpaque(true);
        btnSVLogin.setContentAreaFilled(true);
        btnSVLogin.setBorderPainted(false);
        btnSVLogin.setFocusPainted(false);
        jPanel5.add(btnSVLogin);
        btnExit = new javax.swing.JButton();
        btnExit.setText("Thoát");
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 13));
        btnExit.setBackground(new java.awt.Color(245, 246, 248));
        btnExit.setForeground(new java.awt.Color(107, 114, 128));
        btnExit.setOpaque(true);
        btnExit.setContentAreaFilled(true);
        btnExit.setBorderPainted(false);
        btnExit.setFocusPainted(false);
        jPanel5.add(btnExit);
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        btnSVLogin.addActionListener(this::btnSVLoginActionPerformed);
        btnExit.addActionListener(this::btnExitActionPerformed);


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/ptit-logo.png")).getImage());
        setTitle("PTIT | Đăng nhập giảng viên");

        javax.swing.GroupLayout cardLayout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(cardLayout);
        cardLayout.setHorizontalGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleDe2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gvLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gvPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        cardLayout.setVerticalGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(titleDe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(6, 6, 6)
            .addComponent(titleDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(8, 8, 8)
            .addComponent(gvLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(16, 16, 16)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(8, 8, 8)
            .addComponent(gvPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24)
            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSVLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSVLoginActionPerformed
        // TODO add your handling code here:
        DangNhapSV sv = new DangNhapSV();
        sv.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btnSVLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (!btnLogin.isEnabled()) {
            return;
        }
        String username = gvLogin.getText().trim();
        String password = new String(gvPassword.getPassword());
        
        if(username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập username và password !");
            return;
        }
        btnLogin.setEnabled(false);
        btnSVLogin.setEnabled(false);
        btnLogin.setText("Đang đăng nhập...");

        // Phần này chạy nền để khi chờ SQL, cửa sổ vẫn bấm được.
        new SwingWorker<Void, Void>() {
            sessionGiaoVien giaoVien;
            String thongBao;

            @Override
            protected Void doInBackground() {
                try (Connection ketnoi = connection.getConnectionGV(username, password);
                     CallableStatement cs = ketnoi.prepareCall("{call dbo.SP_LayThongTinGiaoVien()}")) {
                    cs.setQueryTimeout(15);
                    try (ResultSet rs = cs.executeQuery()) {
                        if (rs.next()) {
                            giaoVien = new sessionGiaoVien();
                            giaoVien.setMaGV(rs.getString("MAGV").trim());
                            giaoVien.setHo(rs.getString("HO").trim());
                            giaoVien.setTen(rs.getString("TEN").trim());
                            giaoVien.setSoDTLL(rs.getString("SODTLL"));
                            giaoVien.setDiaChi(rs.getString("DIACHI"));

                            thongBao = "Đăng nhập thành công!\nChào mừng "
                                    + giaoVien.getHo() + " " + giaoVien.getTen() + "!";
                        } else {
                            thongBao = "Tài khoản không tồn tại !";
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    giaoVien = null;
                    thongBao = "Lỗi đăng nhập: " + e.getMessage();
                    if (e instanceof SQLException && ((SQLException) e).getErrorCode() == 18456) {
                        thongBao = "Sai tên tài khoản hoặc mật khẩu !";
                    }
                }
                return null;
            }

            // Khi SQL làm xong, quay lại giao diện để hiện thông báo.
            @Override
            protected void done() {
                btnLogin.setText("Đăng nhập");
                btnLogin.setEnabled(true);
                btnSVLogin.setEnabled(true);
                if (!isDisplayable()) {
                    return;
                }
                JOptionPane.showMessageDialog(DangNhap.this, thongBao);
                if (giaoVien != null) {
                    TrangChu tc = new TrangChu(giaoVien);
                    tc.setVisible(true);
                    DangNhap.this.dispose();
                }
            }
        }.execute();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DangNhap().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel titleDe2;
    private javax.swing.JLabel titleDangNhap;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField gvLogin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField gvPassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton btnSVLogin;
    private javax.swing.JButton btnExit;
    // End of variables declaration//GEN-END:variables
}
